services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    env_file:
      - ./.env
    networks:
      - inception
    ports:
      - "80:80"
    volumes:
      - web:/var/www/wordpress:ro
    depends_on:
      - wordpress
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    env_file:
      - ./.env
    networks:
      - inception
    volumes:
      - db:/var/lib/mysql:rw
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    env_file:
      - ./.env
    networks:
      - inception
    depends_on:
      - mariadb
    volumes:
      - web:/var/www/wordpress:rw
networks:
  inception:

volumes:
  # TODO: bind the volumes to /home/obenchkr
  db:
  web:
