services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    restart: always
    env_file:
      - ./.env
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress:ro
      - adminer:/var/www/adminer:ro
    depends_on:
      - wordpress
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    restart: always
    env_file:
      - ./.env
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql:rw
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    restart: always
    env_file:
      - ./.env
    networks:
      - inception
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress:rw
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    image: redis
    restart: always
    env_file:
      - ./.env
    networks:
      - inception
    volumes:
      - redis:/var/lib/redis:rw
  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    image: adminer
    restart: always
    env_file:
      - ./.env
    networks:
      - inception
    volumes:
      - adminer:/var/www/adminer:rw
networks:
  inception:

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/obenchkr/data/mariadb
      o: rbind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/obenchkr/data/wordpress
      o: rbind
  redis:
    driver: local
    driver_opts:
      type: none
      device: /home/obenchkr/data/redis
      o: rbind
  adminer:
    driver: local
    driver_opts:
      type: none
      device: /home/obenchkr/data/adminer
      o: rbind
