services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    restart: always
    env_file:
      - ./.env
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - web:/var/www/wordpress:ro
    depends_on:
      - wordpress
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    restart: always
    env_file:
      - ./.env
    networks:
      - inception
    volumes:
      - db:/var/lib/mysql:rw
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    restart: always
    env_file:
      - ./.env
    networks:
      - inception
    depends_on:
      - mariadb
    volumes:
      - web:/var/www/wordpress:rw
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    image: redis
    restart: always
    env_file:
      - ./.env
    networks:
      - inception
    volumes:
      - redis:/var/lib/redis:rw
networks:
  inception:

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/obenchkr/data/db
      o: rbind
  web:
    driver: local
    driver_opts:
      type: none
      device: /home/obenchkr/data/web
      o: rbind
  redis:
    driver: local
    driver_opts:
      type: none
      device: /home/obenchkr/data/redis
      o: rbind
