#! /bin/sh

set -e

mariadbd&

mysql <<-EOF

ALTER USER 'root'@'localhost' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD';
DROP USER IF EXISTS 'root'@'%';

CREATE DATABASE $MYSQL_DATABASE;

CREATE USER '$MYSQL_USERNAME'@'localhost' IDENTIFIED BY '$MYSQL_PASSWORD';
CREATE USER '$MYSQL_USERNAME'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';

GANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '$MYSQL_USERNAME'@'localhost';
GANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '$MYSQL_USERNAME'@'%';

FLUSH PRIVILEGES;

EOF

killall -TERM mariadbd

exec mariadbd
